# Stage 0, "build-stage", based on Node.js, to build and compile the frontend
FROM tiangolo/node-frontend:10 as build-stage
WORKDIR /app
COPY package*.json /app/
RUN npm install
COPY ./ /app/

#Testing command
#RUN CI=true npm test
RUN npm run build

# Stage 1, based on Nginx, to have only the compiled app, ready for production with Nginx
FROM nginx:1.15
COPY --from=build-stage /app/build/ /usr/share/nginx/html
# Copy the default nginx.conf provided by tiangolo/node-frontend
COPY --from=build-stage /nginx.conf /etc/nginx/conf.d/default.conf

# # Stage 1, based on Nginx, to have only the compiled app, ready for production with Nginx
# FROM nginx
# COPY --from=build-stage /app/build/ /usr/share/nginx/html

# # Copy the default nginx.conf
# COPY ./nginx.conf /etc/nginx/conf.d/default.conf
# EXPOSE 80

# # FROM nginx:1.15.2-alpine
# # RUN ls .
# # COPY /app/build /var/www
# # COPY ./nginx.conf /etc/nginx/nginx.conf
# # EXPOSE 80
# # ENTRYPOINT [ "nginx","-g","deamon off;" ]