version: '3'
services:
  api:
    image: cryptolabzapi
    working_dir: /usr/src/app
    build: .
    networks:
      - backend
    ports:
      - "3000:3000"

  web-cli:
    image: cryptolabzapi
    networks:
      - backend
    command: sh

networks:
  backend:
    driver: bridge