version: '3'
services:
  api:
    image: cryptolabzapi
    working_dir: /usr/src/app
    build: .
    networks:
      - backend
    ports:
      - "3001:3001"
    volumes:
      - ./:/usr/src/app

  web-cli:
    image: cryptolabzapi
    networks:
      - backend
    command: sh

networks:
  backend:
    driver: bridge